
[window]
padding = { x = 20, y = 20 }
decorations = "Buttonless"

[font]
size = 14
normal = { family = "Iosevka Nerd Font" }

[selection]
save_to_clipboard = true

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
