enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = "tiles"

start-at-login = true

accordion-padding = 70

after-startup-command = [
  "exec-and-forget borders"
]

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 35
outer.right = 35
outer.top = 15
outer.bottom = 25

[mode.main.binding]
alt-comma = "layout tiles horizontal vertical"
alt-period = "layout accordion vertical horizontal"

alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"

alt-ctrl-h = ["join-with left", "mode main"]
alt-ctrl-j = ["join-with down", "mode main"]
alt-ctrl-k = ["join-with up", "mode main"]
alt-ctrl-l = ["join-with right", "mode main"]

alt-minus = "resize smart -200"
alt-equal = "resize smart +200"

alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"

alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"

alt-shift-s = "mode service"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"] # reset layout
f = ["layout floating tiling", "mode main"] # Toggle between floating and tiling layout
